
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dal
{

using System;
    using System.Collections.Generic;
    
public partial class Customers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Customers()
    {

        this.Opinion = new HashSet<Opinion>();

        this.ProductsToCustomers = new HashSet<ProductsToCustomers>();

        this.TasksToCustomer = new HashSet<TasksToCustomer>();

    }


    public int id { get; set; }

    public string mail { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public string password { get; set; }

    public string src_profile { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Opinion> Opinion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductsToCustomers> ProductsToCustomers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TasksToCustomer> TasksToCustomer { get; set; }

}

}
