
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dal
{

using System;
    using System.Collections.Generic;
    
public partial class halls
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public halls()
    {

        this.Img = new HashSet<Img>();

        this.Opinion = new HashSet<Opinion>();

        this.ProductsToCustomers = new HashSet<ProductsToCustomers>();

    }


    public int id { get; set; }

    public string name { get; set; }

    public string phone { get; set; }

    public Nullable<int> minInvited { get; set; }

    public Nullable<int> maxInvited { get; set; }

    public Nullable<int> minPrice { get; set; }

    public Nullable<int> maxPrice { get; set; }

    public string description { get; set; }

    public string src { get; set; }

    public string srcLogo { get; set; }

    public int idtype { get; set; }

    public int idArea { get; set; }

    public int idAddress { get; set; }

    public int idKashrut { get; set; }

    public int idInvited { get; set; }



    public virtual Address Address { get; set; }

    public virtual Area Area { get; set; }

    public virtual Invited Invited { get; set; }

    public virtual Kashrut Kashrut { get; set; }

    public virtual HallType HallType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Img> Img { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Opinion> Opinion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProductsToCustomers> ProductsToCustomers { get; set; }

}

}
