

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Dal
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WeddingEntities : DbContext
{
    public WeddingEntities()
        : base("name=WeddingEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Address> Address { get; set; }

    public virtual DbSet<Area> Area { get; set; }

    public virtual DbSet<Categories> Categories { get; set; }

    public virtual DbSet<ContactUs> ContactUs { get; set; }

    public virtual DbSet<Customers> Customers { get; set; }

    public virtual DbSet<halls> halls { get; set; }

    public virtual DbSet<HallType> HallType { get; set; }

    public virtual DbSet<Img> Img { get; set; }

    public virtual DbSet<Invited> Invited { get; set; }

    public virtual DbSet<Kashrut> Kashrut { get; set; }

    public virtual DbSet<Opinion> Opinion { get; set; }

    public virtual DbSet<ProductsToCustomers> ProductsToCustomers { get; set; }

    public virtual DbSet<Service> Service { get; set; }

    public virtual DbSet<ServToSupp> ServToSupp { get; set; }

    public virtual DbSet<Suppliers> Suppliers { get; set; }

    public virtual DbSet<Tasks> Tasks { get; set; }

    public virtual DbSet<TasksToCustomer> TasksToCustomer { get; set; }

}

}

